spring.application.name=work

spring.datasource.url=jdbc:sqlserver://explojr5;databaseName=shopping_cart_db;encrypt=true;trustServerCertificate=true;integratedSecurity=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.error.include-stacktrace=never